### PR TITLE
Fix for 12/1/2022 TF2 Update

### PR DESCRIPTION
**Pull request by Batfoxkid**
A byte was also changed in the latest update causing the extension to fail.

### CODE REVIEW

**Comment by Naleksuh** [comment]
@Batfoxkid Does this also change the extension binaries and not just the gamedata?

**Comment by Batfoxkid** [comment]
> @Batfoxkid Does this also change the extension binaries and not just the gamedata?

The extension would have to be recompiled.

**Comment by Naleksuh** [comment]
Ah OK. Looks like the latest release was in 2018 and I don't have the tools to compile them myself (IIRC they require external software which is paid). I don't know if @Pelipoika is planning to compile them or not?

**Comment by Pelipoika** [comment]
I don't have plans on compiling this, if someone does they can give me the bins and ill make a new release

**Comment by caxanga334** [comment]
@Pelipoika Compiled for SM 1.11 & SM 1.12 with MSVC 1934.
[PathFollower_1.11.zip](https://github.com/Pelipoika/PathFollower/files/10144333/PathFollower_1.11.zip)
[PathFollower_1.12.zip](https://github.com/Pelipoika/PathFollower/files/10144336/PathFollower_1.12.zip)

**Comment by Pelipoika** [comment]
I published your zips in a new release

**Comment by Naleksuh** [comment]
@caxanga334 Have you tried on 1.11? For me, this makes all bots fail to work with them typically just walking straight forward into walls etc even on officially supported bot maps, while regular bots with tf_bot_add walk around fine.

If you don't have this problem on 1.12, I guess I'll try using that.

**Pull request merged**
